<div style="margin-top: 80px;">
    <div style="background: linear-gradient(100deg, rgba(0,0,0,0.8) 0%, rgba(0,0,0,0.8) 100%), url('https://www.real-estate.ca/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-11.webp'); background-size: cover; min-height: 300px; background-position: center; display: flex; align-items: center; padding: 10%; border-radius: 3px; box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; margin-bottom: 30px;">
        <h2 style="color: #f9f9f9; margin-bottom: 0; padding-bottom: 0; font-size: 35px; line-height: 1.2; text-shadow: 0px 0px 2px #FFFFFF;">
            Capitol Hill Real Estate &mdash; <span style="text-transform: initial;"> a beautiful residential neighbourhood in Calgary’s northwestern quadrant, just north of the Trans-Canada Highway. </span>
        </h2>
    </div>
    <div class="grid_12">
        <div class="x6">
            <p>Welcome to Capitol Hill, a beautiful residential neighbourhood in Calgary’s northwestern quadrant, just north of the Trans-Canada Highway. A wide variety of houses are available here for sale – and you are sure to find one that fits your family’s requirements and budget. Capitol Hill is in a prime location, close to some of the city’s best shopping – North Hill Centre and Market Mall. For fitness, residents have access to Foothills Athletic Park and Confederation Park is located within the community. Capitol Hill has a very active community association that organizes and hosts various programs to bring residents together.</p>
            <p>Capitol Hill’s children are served by several schools in and around the community. The neighbourhood is also close to SAIT, ACAD, and the University of Calgary, making it the ideal community for students.</p>
            <p>McMahon Stadium is a short drive from the community, and residents catch their favourite games live here. The Foothills Athletic Park and the Olympic Oval are close.</p>
            <p>The neighbourhood’s borders are Confederation Park South Boundary (north), 10th Street (east), 16th Avenue (south), and 19th Street, 24th Avenue, 18th Street, and 17th Avenue (west).</p>
        </div>
        <div class="x6 last" style="display: grid; grid-template-columns: 1fr 1fr; gap: 3px; justify-items: center;">
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-24.webp' alt='Front view of Capitol Hill School with trees and metal black fence infront' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-25.webp' alt='Street view of a modern design residential in blue an maroon color with landscaped frontyard' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-26.webp' alt='Closer view of the modern multi level residential  near the street' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-28.webp' alt='Street view near Capitol Hill residential area' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-29.webp' alt='Street view of multi level residential area with tall trees and tall plant ornaments in the front yard' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-30.webp' alt='Residential area streets in Capitol Hill' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-31.webp' alt='Back entrance of Capitol Hill Community Centre with a lot of cars parked and truck for Lino  catering' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-32.webp' alt='Closer view of the building and back door of Capitol Hill Community Centre' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-50.webp' alt='Uphill street with electricity poles an wires above and tall trees on each side' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/houses/capital-hill-wm-51.webp' alt='Downhill grassy green leading to the back entrance of residential building in red colored wall' width='176' height='117'>

        </div>
    </div>
</div><!-- Capitol Hill Introduction -->