<div style="margin-top: 80px;">
    <h2>Amenities in Capitol Hill &mdash; Live, Work, &amp; Play</h2>
    <div class="grid_12">
        <div class="x6" style="display: grid; grid-template-columns: 1fr 1fr; gap: 3px; margin-bottom: 50px;">
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-10.webp' alt='Street view in Capitol Hill with lamp post and tall trees on each side of the street' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-11.webp' alt='Canmore Park signage stand in the middle of grassy with beautifully landscaped design of flower below and surrounded by tall pine trees' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-12.webp' alt='Wide view of Canmore Park near the street and cars parked on the side' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-13.webp' alt='Street view of Holy Cross Angelican Parish building with glass doors an windows and uphill pathway infront' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-14.webp' alt='Back view of Holy Cross Angelican Parish building with a parking lot ' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-15.webp' alt='Scenic view of a golf course at the back of the mesh fence' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-16.webp' alt='Narrow curve street in the side of the golf course and grassy green' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-17.webp' alt='Playground in the beach sand with a bench in the middle of grassy green' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-18.webp' alt='Wide grassy green with a playground on the left and plants withorange mesh fence near the wooden tables and chairs' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-19.webp' alt='Wide grassy green play area near the residential area' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-20.webp' alt='Narrow path entrance to the playground with mesh fence and a signage for no pets allowed' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-33.webp' alt='Grassy green with tall trees background and a signage infront that reads Community Orchards ' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-34.webp' alt='Closer view of plant boxes with various flowers and vegetables and a signage for the garden rules' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-35.webp' alt='Plant boxes with different vegetables and a hose stand nearby' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-36.webp' alt='View of a house back deck with tables and chairs near a small playground' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-37.webp' alt='Playground area with colorful swings, slides and mini tables and stools' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-38.webp' alt='Wide grassy green play area with soccer field and goal near establishments' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-39.webp' alt='Wide grassy green with wooden tables and chairs overlooking the back deck of a house' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-40.webp' alt='Swings in beach sand surrounded by tables and chairs nearby' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-41.webp' alt='Front view of Headquarters Provincial Command building near the street with a flag pole infront' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-42.webp' alt='Street view of the Headquarters Provincial Command building with well maintained front yard and bus stop nearby' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-43.webp' alt='Downhill grassy green beside the street with cars parked near residential area' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-44.webp' alt='Downhill grassy green with a narrow pathway in the middle and surrounded by tall trees' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-45.webp' alt='Narrow street in the middle of forest like surrounding and a bench nearby' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-46.webp' alt='Narrow pathway in the middle of grassy green with tall trees, woman walking with her dog' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-47.webp' alt='Bench in the middle of a scenic view of grassy green with tall trees ' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-48.webp' alt='Front view of Confederation Park building entrance with bench, trash bins and signage infront ' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-49.webp' alt='Signage for Confederation Park information and wide parking lot in the background' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-60.webp' alt='Playground in red and blue color surrounding tall trees' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-61.webp' alt='Wide grassy green golf course with wooden fence, small bridge, narrow pathway and surrounded by tall trees' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-8.webp' alt='Parking lot area for Confederation Park' width='176' height='117'>
            <img style='box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;' class='lazyload' data-src='/uploads/agent-1/calgary/central-calgary/capitol-hill/amenities/capital-hill-wm-9.webp' alt='Driving range area with green dividers and a lot of players practicing' width='176' height='117'>
        </div>
        <div class="x6 last">
            <div>
                <h3 style="margin-bottom: 0;">Golf &mdash;</h3>
                <p>Confederation Park Golf Course is a nine-hole golf course with a putting green and a two-level hitting bay. The golf course is a mere three-minute drive from the neighbourhood and is perfect for an afternoon of golf.</p>
            </div>
            <div style="margin-top: 50px;">
                <h3 style="margin-bottom: 0;">Parks &mdash;</h3>
                <p>When you live in Capitol Hill, you will have easy access to Confederation Park, one of northwest Calgary’s prize parks spread over 160 hectares and located along the neighbourhood’s border. This crescent-shaped park was initially called the North Hill Coulee. There is a wetland area that runs across eight hectares. The park features a natural playground for younger children with a 4.5-metre slide, timber steppers, a water pump, and more. The park is also home to a groomed cross-country trail for skiing. Pathways wind their way across the park and are great for walking and hiking. Tennis courts, baseball diamonds, picnic areas, a tobogganing hill, and picnic areas are just some other attractions here.</p>
                <p>For a weekend morning with the family, head to Canmore Park. Often referred to as North Capitol Park, it has a playground, pool, sports field, tennis courts, splash pad, ball diamonds, skiing and snowboarding, a trail, and picnic facilities.</p>
                <p>Banff Trail Park has something for the entire family – a playground, ball diamond, rink, and community garden.</p>
            </div>
            <div style="margin-top: 50px;">
                <h3 style="margin-bottom: 0;">Shopping &mdash;</h3>
                <p>North Hill Centre was set up in 1958 and is Calgary’s oldest mall. The mall has over 100 shops and services and is a fantastic place to hang out with friends. Pick up groceries or flowers, get your workout in, or simply read a book while you sip on a cappuccino at a café. The mall is located on 14th Avenue NW, a short drive from the community, so residents find it very convenient.</p>
                <p>Market Mall in neighboring Varsity is one of Calgary’s indoor malls and is located on Shaganappi Trail NW a short drive from Capitol Hill. The mall has over 200 retail shops, restaurants, and services and is a convenient shopping destination for the entire family. From fashion wear, shoes, and jewelry to groceries, books, and electronics – you can find it all here at Market Mall.</p>
            </div>
            <div style="margin-top: 50px;">
                <h3 style="margin-bottom: 0;">Fitness &mdash;</h3>
                <p>Capitol Hill’s residents are a stone’s throw away from Calgary’s best private health club – Calgary Winter Club. The club features skating rinks, tennis courts, a swimming pool, rock climbing walls, and curling facilities, to name a few. There are fitness facilities available for those who prefer a gym workout. GYMVMT has a location in the North Hill Shopping Center but if you are looking for a free work out check out Louise Riley Park – this park is home to several pieces of gym equipment so you can get in a quick workout with out having to pay a gym membership.</p>
            </div>
            <div style="margin-top: 50px;">
                <h3 style="margin-bottom: 0;">Restaurants and bars &mdash;</h3>
                <p>Capitol Hill is close to a wide variety of restaurants and pubs thanks to is proximity to SAIT. The wide range of options will satisfy any budget or taste some of the nearby restaurants include:</p>
                <ul>
                    <li style="margin-bottom: 0.5rem;">Earls Kitchen + Bar – an upscale chain that serves gourmet burgers, global comfort food, wines, beers, and cocktails.</li>
                    <li style="margin-bottom: 0.5rem;">The Artist Lounge</li>
                    <li style="margin-bottom: 0.5rem;">Super Smash Café</li>
                    <li style="margin-bottom: 0.5rem;">Tipperary’s Pub</li>
                </ul>
            </div>
        </div>
    </div>
</div><!-- Capitol Hill Amenities -->