<div style="margin-top: 80px;">
    <h2>Amenities in Cliff Bungalow &mdash; Live, Work, &amp; Play</h2>
    <div class="grid_12">
        <div class="x6" style="display: grid; grid-template-columns: 1fr 1fr; gap: 3px; margin-bottom: 50px;">
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-12.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-12.webp" alt="Wide grassy green near the Cliff Bungalow residential area" width="176" height="117"></a>
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-13.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-13.webp" alt="Cliff Bungalow community garden with plant boxes and different plants and vegetables" width="176" height="117"></a>
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-14.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-14.webp" alt="Side of a building with blue tables and chairs near the community garden" width="176" height="117"></a>
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-15.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-15.webp" alt="Busy residential street full of cars parked near a fenced graden" width="176" height="117"></a>
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-16.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-16.webp" alt="Wide grassy green near the community garden and residential in the uphill land on the right" width="176" height="117"></a>
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-29.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-29.webp" alt="Fenced grassy green with kids playing sports and tall buildings on the background" width="176" height="117"></a>
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-6.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/amenities/cliff-bungalow-wm-6.webp" alt="Park in the middle of grassy green and tall trees with buildings on the background" width="176" height="117"></a>
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/schools/cliff-bungalow-wm-20.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/schools/cliff-bungalow-wm-20.webp" alt="Western Canada HIghschool building and entrance, tall pine trees and flag infront, tall stone ornament in the middle of grassy gren" width="176" height="117"></a>
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/schools/cliff-bungalow-wm-21.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/schools/cliff-bungalow-wm-21.webp" alt="Closer view of Western Canada Highschool entrance and building" width="176" height="117"></a>
            <a href="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/schools/cliff-bungalow-wm-10.webp" data-fslightbox><img style="box-shadow: rgba(50, 50, 93, 0.25) 0px 13px 27px -5px, rgba(0, 0, 0, 0.3) 0px 8px 16px -8px; border-radius: 3px; display: inline-block;" class="lazyload" data-src="/uploads/agent-1/calgary/central-calgary/cliff-bungalow/schools/cliff-bungalow-wm-10.webp" alt="Front view of Cliff Bungalow elementary school building with tall trees, flag pole and plants in front" width="176" height="117"></a>
        </div>
        <div class="x6 last">
            <div>
                <h3 style="margin-bottom: 0;">Shopping &mdash;</h3>
                <p>Cliff Bungalow is located close to a number of shopping attractions. These include Nikola, Lululemon Athletica, Alia, Gravity Pope Co Ltd and Sucre Body Sugaring Boutique Ltd. The neighbourhood is home to the 4 Street commercial district and 17 Avenue, both of which provide many shopping attractions. </p>
            </div>
            <div style="margin-top: 50px;">
                <h3 style="margin-bottom: 0;">Parks &mdash;</h3>
                <p>Cliff Bungalow has a number of playgrounds and green spaces in and around the neighbourhood. These include 24 Ave SW Playground, MNP Community & Sport Centre (one of Canada's top training centres that is home to 3 Pools), 1 Playground, 5 Gyms and a weight room. There is also Beaulieu Gardens, a formal terraced garden surrounding the historic Lougheed House. Great for a family outing, the Beaulieu Gardens are also home to a museum. For residents searching for picnic facilities, Rouleauville Square located facing St. Mary's Cathedral provides excellent grounds.</p>
            </div>
        </div>
    </div>
</div><!-- Cliff Bungalow Amenities -->